### PR TITLE
Upgrade dependencies

### LINKED ISSUE #835: Pywb fails to install on 3.11 & 3.12 (at least on M1 Macs)
This is the output I got when I did `pyenv shell 3.11.2` and `pip install pywb`:

```
      ld: warning: -undefined dynamic_lookup may not work with chained fixups
      building 'gevent._gevent_c_greenlet_primitives' extension
      clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Users/yousuf/.pyenv/versions/3.11.2/include/python3.11 -I/Users/yousuf/.pyenv/versions/3.11.2/include/python3.11 -I/private/var/folders/55/p5p54zl95l123gy3xq4c68w00000gn/T/pip-install-muunm6ds/gevent_950a4868be3743bda7446af46329f5f0/deps -Isrc/gevent -Isrc/gevent/libev -Isrc/gevent/resolver -I. -I/Users/yousuf/.pyenv/versions/3.11.2/include/python3.11 -c src/gevent/_greenlet_primitives.c -o build/temp.macosx-13.0-arm64-cpython-311/src/gevent/_greenlet_primitives.o -Wno-unreachable-code -Wno-deprecated-declarations -Wno-incompatible-sysroot -Wno-tautological-compare -Wno-implicit-function-declaration -Wno-unused-value -Wno-macro-redefined
      In file included from src/gevent/_greenlet_primitives.c:1080:
      /private/var/folders/55/p5p54zl95l123gy3xq4c68w00000gn/T/pip-install-muunm6ds/gevent_950a4868be3743bda7446af46329f5f0/deps/greenlet/greenlet.h:42:5: error: unknown type name 'CFrame'
          CFrame* cframe;
          ^
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gevent
Failed to build gevent
ERROR: Could not build wheels for gevent, which is required to install pyproject.toml-based projects

```

### PR DESCRIPTION
**Pull request by edsu**
**This is a draft since 4 tests are failing after the upgrades...**
---

## Description

Upgrade various dependencies (gevent, werkzeug, markupsafe, jinja2, flask and httpbin) with the goal of fixing builds with Python v3.11 and higher.

## Motivation and Context

I spent a bit of time trying to let gevent float to 3.1.2 and working through the effects of running pip install -r requirements.txt.

The good news is gevent v22.10.2 installs under Python3.11 now. But installing the latest werkzeug (which is currently unpinned) brings along the need to upgrade markupsafe and jinja2. I worked through the minimal changes to get that working, which mostly involved using pass_context instead of contextfunction.

The bad news is that the tests installed an old version of flask, which pulled in an old version of werkzeug which breaks things again. The reason why flask < v2 is installed is to get the old werkzeug which is needed by httpbin, which appears to be dead?

I think we could pin back werkzeug in our requirements.txt to solve this. But it seems like we would just be forestalling the inevitable need to upgrade? The approach taken here is to install a fork of httpbin for testing which has been updated to work with the latest werkzeug.

Fixes #835

## Types of changes
- [ ] Replay fix (fixes a replay specific issue)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added or updated tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by FraMecca** [comment]
Overall there are only 5 tests failing on my branch but they are all related to path rewriting. I need help fixing those because I have no experience with that part of the codebase

**Comment by edsu** [comment]
@FraMecca I see 4 tests failing in my Python 3.11 dev environment:

```
FAILED tests/test_live_rewriter.py::TestLiveRewriter::test_live_bad_content_length[frame] - webtest.app.AppError: Bad response: 400 Bad Request (not 200)
FAILED tests/test_live_rewriter.py::TestLiveRewriter::test_live_bad_content_length[non-frame] - webtest.app.AppError: Bad response: 400 Bad Request (not 200)
FAILED tests/test_live_rewriter.py::TestLiveRewriter::test_live_bad_content_length_with_range[frame] - webtest.app.AppError: Bad response: 400 Bad Request (not 206)
FAILED tests/test_live_rewriter.py::TestLiveRewriter::test_live_bad_content_length_with_range[non-frame] - webtest.app.AppError: Bad response: 400 Bad Request (not 206)
```

I'm pretty sure these are related to me switching to a fork of httpbin. I need to get these tests resolved now since I'm having trouble installing greenlet v1 on the latest debian.

**Comment by FraMecca** [comment]
@edsu so we have the same failures on our branches. I don't understand how you are able to pull that without switching to  a py3 version of pyamf. What do you plan to do for httpbin?

**Comment by edsu** [comment]
@FraMecca I'm currently using a fork of httpbin that has been updated: https://github.com/webrecorder/pywb/blob/upgrade-dependencies/test_requirements.txt#L9

I updated this PR to replace `werkzeug.wsgi import pop_path_info` with `wsgiref.util import shift_path_info` since the werkzeug team [decided](https://github.com/pallets/werkzeug/pull/2415) it was duplicated there.

I see the problem with pyamf now, but am confused about how it was getting pulled in before. Where do you see that it's a dependency of warcio?

**Comment by edsu** [comment]
I think that perhaps these length tests are failing because spaces are now being removed from JSON responses somewhere in the stack, maybe by the httpbin fork?

Here are a bunch of space related changes I needed to make to get some tests to pass:
https://github.com/webrecorder/pywb/commit/5b72d968717db159cc37a56ee430620f1dcfa161

**Comment by FraMecca** [comment]
@edsu I get 400 instead of 200 on some tests that use httbin, so it might be a different issue

**Comment by FraMecca** [comment]
> It looks like py3AMF is being installed conditionally in the [setup.py](https://github.com/webrecorder/pywb/blob/main/setup.py#L65-L68). Is that not working for you?

It's needed, for the tests, right? In any case porting to py3 wasn't a big effort

**Comment by edsu** [comment]
@FraMecca there is already a Python3 port or pyamf? https://github.com/StdCarrot/Py3AMF

**Comment by edsu** [comment]
It looks like https://github.com/psf/httpbin is being actively maintained by the Python Software Foundation so I'm going to switch to using that.

Sadly, I see it still has the same set of HTTP 400 instead of HTTP 200 errors:

```
FAILED tests/test_live_rewriter.py::TestLiveRewriter::test_live_bad_content_length[frame] - webtest.app.AppError: Bad response: 400 Bad Request (not 200)
```

But at least if a change in httbin is needed it is feasible to get it applied. The original repository is abandoned.

**Comment by edsu** [comment]
Sadly it appears that httpbin is no longer able to return invalid `Content-Length` headers:

```
curl -i -X GET "http://localhost:8080/response-headers?content-length=149,149" -H "accept: application/json"
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Type: text/html
Content-Length: 141

<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>

  </body>
</html
```

This is what appears in the docker console when run against the psf/httpbin:

```
[2023-09-22 10:21:01 +0000] [7] [ERROR] Error handling request /response-headers?content-length=149,149
Traceback (most recent call last):
  File "/opt/httpbin/lib/python3.10/site-packages/gunicorn/workers/base_async.py", line 55, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/opt/httpbin/lib/python3.10/site-packages/gunicorn/workers/ggevent.py", line 128, in handle_request
    super().handle_request(listener_name, req, sock, addr)
  File "/opt/httpbin/lib/python3.10/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/httpbin/lib/python3.10/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/httpbin/lib/python3.10/site-packages/flask/app.py", line 2197, in wsgi_app
    return response(environ, start_response)
  File "/opt/httpbin/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 579, in __call__
    start_response(status, headers)
  File "/opt/httpbin/lib/python3.10/site-packages/gunicorn/http/wsgi.py", line 243, in start_response
    self.process_headers(headers)
  File "/opt/httpbin/lib/python3.10/site-packages/gunicorn/http/wsgi.py", line 264, in process_headers
    self.response_length = int(value)
ValueError: invalid literal for int() with base 10: '149,149'
```

Maybe the older version of httpbin wasn't so strict?

**Comment by aquatix** [comment]
Any news on this? We would like to upgrade our old Debian 11 servers to 12 :)

**Comment by tw4l** [comment]
> Any news on this? We would like to upgrade our old Debian 11 servers to 12 :)

Hi, thanks for your patience and to @edsu for starting this branch! Apologies for the long delay on taking this up, we've been very focused on Browsertrix of late and are a small team. I'm planning to merge this into main soon with some other fixes/features and we should put out a new release shortly!

**Comment by tw4l** [comment]
Pinning `gevent==23.9.0` and `greenlet>=2.0.2` to specific versions because `httpbin` requires `greenlet < 3` for now. We can update to latest/greenlet 3 when the PSF-maintained httpbin updates, or contribute that separately.

**Comment by tw4l** [comment]
Note that [werkzeug 2.3.0 dropped support for Python 3.7](https://werkzeug.palletsprojects.com/en/3.0.x/changes/#version-2-3-0); if we want to continue to support Python < 3.8, we'd need to pin to `werkzeug==2.2.3`, which does not support Python 3.12 so may become an issue shortly.

**Comment by tw4l** [comment]
It's also worth noting that `werkzeug` [dropped support for Python 2 and Python 3.5 in version 2.0.0](Drop support for Python 2 and 3.5), released in 2021 and we previously didn't have the version pinned, so likely our claim to support Python 2 and <3.6 hasn't actually been true for a little while. There are almost certainly some additional things that can be dropped accordingly, but I didn't want the scope of this PR to expand too much so that might be better done in a follow-up.

**Comment by tw4l** [comment]
We decided to support Python 3.7-3.11 in the next release, and will drop Python 3.7, add Python 3.12, and upgrade dependencies further in the following release. I will make an issue to document what will be needed at that point.

**Review by ikreymer — APPROVED** [review]
Nice work! This is an important step in moving pywb forward!

**Comment by aquatix** [comment]
Great work @tw4l !
