### PR TITLE
Upgrade greenlet and gevent for Python 3.12 support

### LINKED ISSUE #954: Installation results in Greenlet build error (Linux Mint 22.1 / Python 3.12.3)
## Describe the bug

Installation of latest Pywb fails with build error for greenlet, installable package.

## Steps to reproduce the bug

I tried to install Pywb with the following command:

```
pipx install pywb
```

Result:

```
Fatal error from pip prevented installation. Full pip output in file:
    /home/johan/.local/state/pipx/log/cmd_2025-09-23_13.39.59_pip_errors.log

pip seemed to fail to build packages:
    greenlet
    installable

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    src/greenlet/greenlet.h:8:10: fatal error: Python.h: No such file or directory
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
    error: failed-wheel-build-for-install

Error installing pywb.
```

See also attached [cmd_2025-09-23_13.39.59_pip_errors.log](https://github.com/user-attachments/files/22493033/cmd_2025-09-23_13.39.59_pip_errors.log) for details.

## Environment

- OS: Linux Mint 22.1 Xia
- Python version:  3.12.3

### PR DESCRIPTION
**Pull request by ldko**
## Description
This adjusts the requirements.txt file for versions of greenlet and gevent that look like they work with Python 3.12 by specifying different versions based on which Python version is installing them. Selected versions are based on the Changes lists for those packages and takes into account the [httbin dependencies](https://github.com/psf/httpbin/blob/e32f9933af1386f580d737578e1051d656e8d4c7/pyproject.toml#L37) (httpbin now supports Python 3.12).

## Motivation and Context
This is to make it minimally viable to run pywb with Python 3.12. It would fix #954. 

I ran tests locally, but no matter with this requirements change or not, on various versions of python, 3 tests related to live video stuff (youtube) fail. I see these tests are marked to be skipped though when run via CI.

## Types of changes
- [ ] Replay fix (fixes a replay specific issue)
- [x] Bug fix (non-breaking change which fixes an issue--not really a bug, but there is an issue open to address this)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added or updated tests to cover my changes.
- [x] All new and existing tests passed (via CI they pass, locally the same live video/youtube related tests fail for me that failed before this change).

### CODE REVIEW

**Comment by axllent** [comment]
@tw4l & @ikreymer would it be possible to get a new official release (including official Docker image) with this patch please? There is a [critical 9.8 CVE](https://nvd.nist.gov/vuln/detail/CVE-2023-41419) in gevent (22.10.2) which this PR resolves with the python version bump. Thank you very much.
